name:                femtoparsec
version:             0.1.0.0
github:              "githubuser/femtoparsec"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/femtoparsec#readme>

dependencies:
- base >= 4.7 && < 5
- base >=4.14 && <4.16
- text >= 1.2.4.0 && < 1.3
- mtl >= 2.2.2 && < 2.3
- split >= 0.2.3.4 && < 0.2.4

library:
  source-dirs: src

executables:
  femtoparsec-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - femtoparsec
    - base >=4.14 && <4.16
    - text >= 1.2.4.0 && < 1.3
    - mtl >= 2.2.2 && < 2.3
    - split >= 0.2.3.4 && < 0.2.4

tests:
  femtoparsec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - femtoparsec
    - base >=4.14 && <4.16
    - text >= 1.2.4.0 && < 1.3
    - hspec >= 2.7 && < 2.8
    - hspec-discover >= 2.7 && < 2.8
    - QuickCheck >= 2.14.1 && < 2.15
